### ISSUE TITLE
Playlists not visible

### ISSUE THREAD

**Issue by eximo84** [jonasmore/JellyJams#14]
I've manually generated playlists. They have been created on the disk and Jellyfin and see them and use them. But Jellyjams doesn't show any playlists and reports 0 have been created.

**Comment by JStuhrAsferg** [comment]
I have the same issue.

**Comment by JStuhrAsferg** [comment]
I'm quite sure that i have mapped the playlists volume into jellyjams. Because when i ssh into the pod and ls on the /playlists i see them all:

```
/playlists $ ls
Alternativa e indie Radio                            This is Foo Fighters!
Alternative & Indie Radio                            This is Gorillaz!
Alternative Radio                                    This is Green Day!
Alternative-Rock Radio                               This is Jack Johnson!
Back to the 1970s                                    This is Jake Bugg!
Back to the 1990s                                    This is Justin Timberlake!
Back to the 2000s                                    This is Kendrick Lamar!
Back to the 2010s                                    This is Limp Bizkit!
Back to the 2020s                                    This is Linkin Park!
Discovery Mix - Jona                                 This is Luis Resto!
Drum & Bass Radio                                    This is Mac Miller!
Electronic Radio                                     This is Macklemore & Ryan Lewis!
Elettronica Radio                                    This is Macklemore!
Folk Rock Radio                                      This is Mark Batson!
Genre Mix - Jona                                     This is Maroon 5!
Hip Hop Radio                                        This is Mike Elizondo!
Hip-Hop Radio                                        This is My Chemical Romance!
Indie Radio                                          This is Mø!
Pop Radio                                            This is Nirvana!
Pop, Rock, Alternatif et Indé Radio                  This is Original Broadway Cast Featuring Green Day!
R&B Radio                                            This is Pink Floyd!
Rap Radio                                            This is Rag'n'Bone Man!
Rap, Hip-Hop Radio                                   This is Red Hot Chili Peppers!
Recent Favorites - Jona                              This is Rihanna!
Reggae Radio                                         This is Sabrina Carpenter!
Reggae, Pop Radio                                    This is Sean Paul!
Rock Radio                                           This is Stephen Marley!
This is Bob Marley & The Wailers!                    This is Steve King!
This is Bob Marley and The Wailers!                  This is The Lonely Island!
This is Chase & Status!                              This is Tones and I!
This is Chronixx!                                    This is Tyler, the Creator!
This is Eminem!                                      Top Tracks - Jona
/playlists $ 
```

**Comment by Druntar** [comment]
I am seeing this behavior as well. The application seems to run correctly. Playlists are generated and appear in Jellyfin. However, JellyJams shows 0 playlists to manage.

**Comment by eximo84** [comment]
One thing to note, im not using Jellyfin in docker... its running on an LXC so separate. However the paths match correctly but wondering if there is something there?

From my .env

/mnt/filestore-media is an SMB share mounted to the VM that runs JellyJams.
/mnt/media is mounted directly to the LXC

Both paths go to the same underlying file structure.

```
PLAYLIST_DIR_HOST=/mnt/filestore-media/Music/Playlists
MUSIC_DIR_HOST=/mnt/filestore-media/Music
MUSIC_DIR_CONTAINER=/mnt/media/music
```

**Comment by eximo84** [comment]
ok, so ive recently wiped my jellyfin instance and setup fresh.  No playlists even though they exist in my music / playlists folder.

Ran the jellyjams container, generated playlists and they are dropped in /var/lib/jellyfin/data/playlists on my LXC.  As such Jellyjams cannot see this folder and im not really sure how it ever will.

im actually unsure how a playlists folder got created in my music folder which contained identical named playlists :?

**Comment by drolex2** [comment]
@eximo84 it is as I explained. For you, you need to set `PLAYLIST_DIR_HOST=/var/lib/jellyfin/data/playlists`
That will map your Jellyfin playlists dir to `/playlists` in JellyJams so that JellyJams can see the playlists.

**Comment by drolex2** [comment]
@JStuhrAsferg 
> I'm quite sure that i have mapped the playlists volume into jellyjams. Because when i ssh into the pod and ls on the /playlists i see them all:

I'm not familiar with your setup. What is the pod? If Jellyfin's internal playlist directory were mapped to /playlists in JellyJams, then it should be working. Did you ls in those listed directories and see actual playlist xml files?

**Comment by eximo84** [comment]
> @eximo84 it is as I explained. For you, you need to set `PLAYLIST_DIR_HOST=/var/lib/jellyfin/data/playlists`
> That will map your Jellyfin playlists dir to `/playlists` in JellyJams so that JellyJams can see the playlists.

But jellyjams and Jellyfin are on different machines. 

Based on this logic, are the variables labelled HOST relating to the Jellyfin server?

Then the variables labelled CONTAINER relate to the Jellyfin server?

I've mapped as you said but jellyjams still isn't showing the playlists. 

Sorry

**Comment by eximo84** [comment]
Yeah. I've docker exec'd into the jellyjams container and the playlists has content but no xml just the cover file. Also this is mapping to the docker container host as I would expect. 

So I think I need to symlink the playlists folder on my Jellyfin LXC to a shared folder which both LXC and Docker Containers can see. 

Will report back.

**Comment by drolex2** [comment]
@eximo84 
> But jellyjams and Jellyfin are on different machines.
> 
> Based on this logic, are the variables labelled HOST relating to the Jellyfin server?
> 
> Then the variables labelled CONTAINER relate to the Jellyfin server?

They are supposed to be on the same machine, or you need some other way to give JellyJams access to Jellyfin's internal playlist folder. The Playlist folder is not a library folder that you map in Jellfin; it is a fixed internal folder.

Host refers to the host machine that runs both Jellyfin and Jellyjams containers. A container path is the path within a container, and we could be taking about Jellyfin or Jellyjams.

**Comment by eximo84** [comment]
> @eximo84 
> > But jellyjams and Jellyfin are on different machines.
> > 
> > Based on this logic, are the variables labelled HOST relating to the Jellyfin server?
> > 
> > Then the variables labelled CONTAINER relate to the Jellyfin server?
> 
> They are supposed to be on the same machine, or you need some other way to give JellyJams access to Jellyfin's internal playlist folder. The Playlist folder is not a library folder that you map in Jellfin; it is a fixed internal folder.
> 
> Host refers to the host machine that runs both Jellyfin and Jellyjams containers. A container path is the path within a container, and we could be taking about Jellyfin or Jellyjams.

Amazing. Thank you for the taking your time to explain this. Like I said, i will try and symlink this and report back.

**Comment by eximo84** [comment]
So i moved my playlists folder from the JF directory to my shared mount... created a symlink to my mount point.

I set the .env values to all point at my docker host VM mount point.

Restarted JF and Jellyjams and everything can see everything :)

```
ln -s /mnt/media/Music/playlists /var/lib/jellyfin/data/playlists
```
